/*

 * Created By: Robert Schmicker

 * Date: 12/22/15

 * File: main.cpp

 * Purpose: 

 The sequence of triangle numbers is generated by adding the natural numbers. 

 So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 

 The first ten terms would be:

 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

 Let us list the factors of the first seven triangle numbers:

 1: 1

 3: 1,3

 6: 1,2,3,6

 10: 1,2,5,10

 15: 1,3,5,15

 21: 1,3,7,21

 28: 1,2,4,7,14,28

 We can see that 28 is the first triangle number to have over five divisors.
 What is the value of the first triangle number to have over five hundred divisors?

 */

#include <iostream>
#include <math.h>

using namespace std;

int NumOfDivisors(int num);

int main(){
    int num = 0;
    int i = 1;
    
    while(NumOfDivisors(num) < 500){
        num += i;
        i++;
    }
    cout << num;
    return 0;
}

int NumOfDivisors(int num){
    int nod = 0;
    int sqrtn = (int)sqrt(num);
    
    for(int i = 1; i<= sqrtn; i++){
        if(num % i == 0){
            nod += 2;
        }
    }
    if (sqrtn * sqrtn == num) {
        nod--;
    }
    
    return nod;
}